export const  SEARCH_FOCUS =  'search_focus'
export const  SEARCH_BLUR =  'search_blur'
export const CHANGE_LIST = 'change_list'
export const MOUSEENTER = 'mouse_enter'
export const MOUSELEAVE = 'mouse_leave'
export const CHANGEPAGE = 'change_page'
